// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace VRCTP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:4fea2206-b212-4ffb-a87b-906e39a3e258
    public partial class GuidancePanel
    {
        
        public const string NAME = "GuidancePanel";
        
        private GuidancePanelData mPrivateData = null;
        
        public GuidancePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new GuidancePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            mData = null;
        }
    }
}
