// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Gamelogic
    {
        public const string BundleName = "gamelogic";
        public const string BGLAYER = "bglayer";
        public const string DEATHZONE = "deathzone";
        public const string LANDEFFECT = "landeffect";
        public const string MAGNETITELAYER = "magnetitelayer";
        public const string PLAYER = "player";
        public const string RAINPREFAB2D = "rainprefab2d";
        public const string STAGELAYER = "stagelayer";
        public const string SUN = "sun";
    }
    public class Gameplay_prefab
    {
        public const string BundleName = "gameplay_prefab";
        public const string GAME = "game";
        public const string GAMEPLAY = "gameplay";
    }
    public class Magnetitelayer_prefab
    {
        public const string BundleName = "magnetitelayer_prefab";
        public const string MAGNETITELAYER = "magnetitelayer";
    }
    public class Music
    {
        public const string BundleName = "music";
        public const string GAME = "game";
        public const string HOME = "home";
    }
    public class Player_prefab
    {
        public const string BundleName = "player_prefab";
        public const string PLAYER = "player";
    }
    public class Sound
    {
        public const string BundleName = "sound";
        public const string BOSSSHAKE = "bossshake";
        public const string BTN = "btn";
        public const string COIN = "coin";
        public const string COIN2 = "coin2";
        public const string DEATH = "death";
        public const string ENEMYDEATH1 = "enemydeath1";
        public const string ENEMYDEATH2 = "enemydeath2";
        public const string FIRE = "fire";
        public const string FOREST = "forest";
        public const string FRUIT = "fruit";
        public const string HERO_HURT = "hero_hurt";
        public const string JUMP = "jump";
        public const string JUMP1 = "jump1";
        public const string JUMP2 = "jump2";
        public const string PROP_BIG = "prop_big";
        public const string SELECT = "select";
        public const string SHAKE = "shake";
        public const string UNUSE1 = "unuse1";
        public const string UNUSE2 = "unuse2";
        public const string UNUSE3 = "unuse3";
        public const string UNUSE4 = "unuse4";
        public const string UNUSE5 = "unuse5";
    }
    public class Stage1
    {
        public const string BundleName = "stage1";
        public const string AIR = "air";
        public const string BG1 = "bg1";
        public const string COMPONENT1 = "component1";
        public const string COMPONENT2 = "component2";
        public const string COMPONENT3 = "component3";
        public const string COMPONENT4 = "component4";
        public const string COMPONENT5 = "component5";
        public const string COMPONENT6 = "component6";
        public const string COMPONENT7 = "component7";
        public const string COMPONENT8 = "component8";
        public const string COMPONENT9 = "component9";
        public const string CUSTOMSTAGE1 = "customstage1";
        public const string CUSTOMSTAGE2 = "customstage2";
        public const string CUSTOMSTAGE3 = "customstage3";
        public const string CUSTOMSTAGE4 = "customstage4";
        public const string CUSTOMSTAGE5 = "customstage5";
        public const string CUSTOMSTAGE6 = "customstage6";
        public const string CUSTOMSTAGE7 = "customstage7";
        public const string CUSTOMSTAGE8 = "customstage8";
        public const string CUSTOMSTAGE9 = "customstage9";
        public const string CUSTOMSTAGE10 = "customstage10";
        public const string CUSTOMSTAGE11 = "customstage11";
        public const string CUSTOMSTAGE12 = "customstage12";
        public const string CUSTOMSTAGE13 = "customstage13";
        public const string CUSTOMSTAGE14 = "customstage14";
        public const string CUSTOMSTAGE15 = "customstage15";
        public const string CUSTOMSTAGEBASIC = "customstagebasic";
        public const string LEFT = "left";
        public const string LOOP = "loop";
        public const string MIDDLE = "middle";
        public const string RIGHT = "right";
        public const string STAGEPATTERN = "stagepattern";
    }
    public class Stage2
    {
        public const string BundleName = "stage2";
        public const string AIR = "air";
        public const string BG2 = "bg2";
        public const string COMPONENT1 = "component1";
        public const string COMPONENT2 = "component2";
        public const string COMPONENT3 = "component3";
        public const string COMPONENT4 = "component4";
        public const string COMPONENT5 = "component5";
        public const string COMPONENT6 = "component6";
        public const string COMPONENT7 = "component7";
        public const string COMPONENT8 = "component8";
        public const string COMPONENT9 = "component9";
        public const string COMPONENT10 = "component10";
        public const string COMPONENT11 = "component11";
        public const string COMPONENT12 = "component12";
        public const string COMPONENT13 = "component13";
        public const string COMPONENT14 = "component14";
        public const string COMPONENT15 = "component15";
        public const string COMPONENT16 = "component16";
        public const string COMPONENT17 = "component17";
        public const string COMPONENT18 = "component18";
        public const string COMPONENT19 = "component19";
        public const string COMPONENT20 = "component20";
        public const string CUSTOMSTAGE1 = "customstage1";
        public const string CUSTOMSTAGE2 = "customstage2";
        public const string CUSTOMSTAGE3 = "customstage3";
        public const string CUSTOMSTAGE4 = "customstage4";
        public const string CUSTOMSTAGE5 = "customstage5";
        public const string CUSTOMSTAGE6 = "customstage6";
        public const string CUSTOMSTAGE7 = "customstage7";
        public const string CUSTOMSTAGE8 = "customstage8";
        public const string CUSTOMSTAGE9 = "customstage9";
        public const string CUSTOMSTAGE10 = "customstage10";
        public const string CUSTOMSTAGE11 = "customstage11";
        public const string CUSTOMSTAGE12 = "customstage12";
        public const string CUSTOMSTAGE13 = "customstage13";
        public const string CUSTOMSTAGE14 = "customstage14";
        public const string CUSTOMSTAGE15 = "customstage15";
        public const string CUSTOMSTAGEBASE = "customstagebase";
        public const string LEFT = "left";
        public const string LOOP = "loop";
        public const string MIDDLE = "middle";
        public const string RIGHT = "right";
        public const string STAGEPATTERN = "stagepattern";
    }
    public class Stage3
    {
        public const string BundleName = "stage3";
        public const string AIR = "air";
        public const string BG3 = "bg3";
        public const string COMPONENT1 = "component1";
        public const string COMPONENT2 = "component2";
        public const string COMPONENT3 = "component3";
        public const string COMPONENT4 = "component4";
        public const string COMPONENT5 = "component5";
        public const string COMPONENT6 = "component6";
        public const string COMPONENT7 = "component7";
        public const string COMPONENT8 = "component8";
        public const string COMPONENT9 = "component9";
        public const string COMPONENT10 = "component10";
        public const string COMPONENT11 = "component11";
        public const string COMPONENT12 = "component12";
        public const string COMPONENT13 = "component13";
        public const string COMPONENT14 = "component14";
        public const string COMPONENT15 = "component15";
        public const string COMPONENT16 = "component16";
        public const string COMPONENT17 = "component17";
        public const string COMPONENT18 = "component18";
        public const string CUSTOMSTAGE1 = "customstage1";
        public const string CUSTOMSTAGE2 = "customstage2";
        public const string CUSTOMSTAGE3 = "customstage3";
        public const string CUSTOMSTAGE4 = "customstage4";
        public const string CUSTOMSTAGE5 = "customstage5";
        public const string CUSTOMSTAGE6 = "customstage6";
        public const string CUSTOMSTAGE7 = "customstage7";
        public const string CUSTOMSTAGE8 = "customstage8";
        public const string CUSTOMSTAGE9 = "customstage9";
        public const string CUSTOMSTAGE10 = "customstage10";
        public const string CUSTOMSTAGE11 = "customstage11";
        public const string CUSTOMSTAGE12 = "customstage12";
        public const string CUSTOMSTAGE13 = "customstage13";
        public const string CUSTOMSTAGE14 = "customstage14";
        public const string CUSTOMSTAGE15 = "customstage15";
        public const string CUSTOMSTAGEBASE = "customstagebase";
        public const string LEFT = "left";
        public const string LOOP = "loop";
        public const string MIDDLE = "middle";
        public const string RIGHT = "right";
        public const string STAGEPATTERN = "stagepattern";
    }
    public class Stage4
    {
        public const string BundleName = "stage4";
        public const string AIR = "air";
        public const string BG4 = "bg4";
        public const string COMPONENT1 = "component1";
        public const string COMPONENT2 = "component2";
        public const string COMPONENT3 = "component3";
        public const string COMPONENT4 = "component4";
        public const string COMPONENT5 = "component5";
        public const string COMPONENT6 = "component6";
        public const string COMPONENT7 = "component7";
        public const string COMPONENT8 = "component8";
        public const string COMPONENT9 = "component9";
        public const string COMPONENT10 = "component10";
        public const string CUSTOMSTAGE1 = "customstage1";
        public const string CUSTOMSTAGE2 = "customstage2";
        public const string CUSTOMSTAGE3 = "customstage3";
        public const string CUSTOMSTAGE4 = "customstage4";
        public const string CUSTOMSTAGE5 = "customstage5";
        public const string CUSTOMSTAGE6 = "customstage6";
        public const string CUSTOMSTAGE7 = "customstage7";
        public const string CUSTOMSTAGE8 = "customstage8";
        public const string CUSTOMSTAGE9 = "customstage9";
        public const string CUSTOMSTAGE10 = "customstage10";
        public const string CUSTOMSTAGE11 = "customstage11";
        public const string CUSTOMSTAGE12 = "customstage12";
        public const string CUSTOMSTAGE13 = "customstage13";
        public const string CUSTOMSTAGE14 = "customstage14";
        public const string CUSTOMSTAGE15 = "customstage15";
        public const string CUSTOMSTAGEPATTERN = "customstagepattern";
        public const string LEFT = "left";
        public const string LOOP = "loop";
        public const string MIDDLE = "middle";
        public const string RIGHT = "right";
        public const string STAGEPATTERN = "stagepattern";
    }
    public class Stagespawnpools
    {
        public const string BundleName = "stagespawnpools";
        public const string STAGE1SPAWNPOOL = "stage1spawnpool";
        public const string STAGE2SPAWNPOOL = "stage2spawnpool";
        public const string STAGE3SPAWNPOOL = "stage3spawnpool";
        public const string STAGE4SPAWNPOOL = "stage4spawnpool";
    }
    public class Uigamepanel_prefab
    {
        public const string BundleName = "uigamepanel_prefab";
        public const string UIGAMEPANEL = "uigamepanel";
    }
    public class Uihelppanel_prefab
    {
        public const string BundleName = "uihelppanel_prefab";
        public const string UIHELPPANEL = "uihelppanel";
    }
    public class Uihomeinfopanel_prefab
    {
        public const string BundleName = "uihomeinfopanel_prefab";
        public const string UIINFOPANEL = "uiinfopanel";
    }
    public class Uihomepanel_prefab
    {
        public const string BundleName = "uihomepanel_prefab";
        public const string UIHOMEPANEL = "uihomepanel";
    }
    public class Uipausepanel_prefab
    {
        public const string BundleName = "uipausepanel_prefab";
        public const string UIPAUSEPANEL = "uipausepanel";
    }
    public class Uisettingpanel_prefab
    {
        public const string BundleName = "uisettingpanel_prefab";
        public const string UISETTINGPANEL = "uisettingpanel";
    }
    public class Uishoppanel_prefab
    {
        public const string BundleName = "uishoppanel_prefab";
        public const string UISHOPPANEL = "uishoppanel";
    }
    public class Uistorypanel_prefab
    {
        public const string BundleName = "uistorypanel_prefab";
        public const string UISTORYPANEL = "uistorypanel";
    }
}
