// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace VRCTP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:29ee8f50-287b-4de3-83ee-dd1c715dcb9d
    public partial class EquippedPanel
    {
        
        public const string NAME = "EquippedPanel";
        
        [SerializeField()]
        public EquippedParent EquippedParent;
        
        [SerializeField()]
        public CheckButton CheckButton;
        
        private EquippedPanelData mPrivateData = null;
        
        public EquippedPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new EquippedPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            EquippedParent = null;
            CheckButton = null;
            mData = null;
        }
    }
}
