// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace VRCTP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:f0d3dddd-3182-40b5-b294-8474094454bd
    public partial class UISceneChooicePanel
    {
        
        public const string NAME = "UISceneChooicePanel";
        
        [SerializeField()]
        public BtnRotation BtnRotation;
        
        [SerializeField()]
        public EnterButton EnterButton;
        
        private UISceneChooicePanelData mPrivateData = null;
        
        public UISceneChooicePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UISceneChooicePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnRotation = null;
            EnterButton = null;
            mData = null;
        }
    }
}
