// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace VRCTP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:9fa1d760-1b91-4323-9562-ba06e6030c50
    public partial class WorkPlacePanel
    {
        
        public const string NAME = "WorkPlacePanel";
        
        [SerializeField()]
        public Guidetext Image;
        
        [SerializeField()]
        public AlreadyRead CloseButton;
        
        private WorkPlacePanelData mPrivateData = null;
        
        public WorkPlacePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new WorkPlacePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Image = null;
            CloseButton = null;
            mData = null;
        }
    }
}
